'use client';

import { useState } from 'react';
import Link from 'next/link';
import CreateKnowledgeBase from '@/app/components/CreateKnowledgeBase';

// This would typically come from an API
interface KnowledgeBase {
  id: string;
  title: string;
  description: string;
  documentCount: number;
}

export default function Home() {
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [knowledgeBases, setKnowledgeBases] = useState<KnowledgeBase[]>([
    {
      id: '1',
      title: 'Project Documentation',
      description: 'Technical documentation and guides for the main project.',
      documentCount: 15,
    },
    {
      id: '2',
      title: 'Research Notes',
      description: 'Collection of research papers and personal notes.',
      documentCount: 8,
    },
  ]);

  const handleCreateKnowledgeBase = (title: string, description: string) => {
    const newKnowledgeBase: KnowledgeBase = {
      id: Date.now().toString(), // This would typically be generated by the backend
      title,
      description,
      documentCount: 0,
    };
    setKnowledgeBases([...knowledgeBases, newKnowledgeBase]);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <header className="mb-8">
        <h1 className="text-4xl font-bold text-gray-900">Knowledge Bases</h1>
        <p className="mt-2 text-gray-600">Create and manage your knowledge bases</p>
      </header>

      <div className="mb-8">
        <button
          onClick={() => setIsCreateModalOpen(true)}
          className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
        >
          Create New Knowledge Base
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {knowledgeBases.map((kb) => (
          <Link
            key={kb.id}
            href={`/knowledge-base/${kb.id}`}
            className="block bg-white rounded-lg shadow-sm p-6 hover:shadow-md transition-shadow"
          >
            <h2 className="text-xl font-semibold text-gray-900 mb-2">{kb.title}</h2>
            <p className="text-gray-600 mb-4">{kb.description}</p>
            <div className="text-sm text-gray-500">
              Documents: {kb.documentCount}
            </div>
          </Link>
        ))}
      </div>

      {knowledgeBases.length === 0 && (
        <div className="text-center py-12">
          <p className="text-gray-600 mb-4">No knowledge bases yet. Create your first one to get started!</p>
          <button
            onClick={() => setIsCreateModalOpen(true)}
            className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
          >
            Create First Knowledge Base
          </button>
        </div>
      )}

      <CreateKnowledgeBase
        isOpen={isCreateModalOpen}
        onClose={() => setIsCreateModalOpen(false)}
        onCreate={handleCreateKnowledgeBase}
      />
    </div>
  );
}
